import { defineConfig, presetAttributify, presetWind3, presetIcons } from 'unocss'
import presetRemToPx from '@unocss/preset-rem-to-px'
// import { getIconData, iconToHTML, iconToSVG, replaceIDs, type IconifyJSON } from "@iconify/utils";
// import lucide from "@iconify-json/lucide/icons.json";
// import stash from "@iconify-json/stash/icons.json";

// 直接以 icons.json 作为 presetIcons 的 custom collection 时，@iconify/utils 的
// getCustomIcon 只认「扁平 iconName → svg 字符串」的映射；而默认的 node loader 在
// VS Code 终端（VSCODE_CWD 被设置）下会被 @unocss/preset-icons 跳过，导致全部图标加载失败。
// 因此这里把每个图标集转成一个惰性 loader 函数，返回可直接使用的 SVG 字符串，
// 在任何环境（含 VS Code 终端）都能稳定加载。
// function createIconLoader(iconSet: IconifyJSON) {
//   return (icon: string): string | undefined => {
//     const data = getIconData(iconSet, icon);
//     if (!data) return undefined;
//     const { body, attributes } = iconToSVG(data, {});
//     return iconToHTML(replaceIDs(body), attributes);
//   };
// }

export default defineConfig({
  presets: [
    presetAttributify(),
    presetWind3(),
    presetIcons({
      collections: {
        // lucide: createIconLoader(lucide),
        // stash: createIconLoader(stash),
        lucide: () => import('@iconify-json/lucide/icons.json').then((m) => m.default),
        stash: () => import('@iconify-json/stash/icons.json').then((m) => m.default),
      },
      scale: 1.2,
      warn: true,
      // 统一图标基线与尺寸（随 font-size 缩放），显式 w-/h- 类优先级更高可覆盖
      extraProperties: {
        display: 'inline-block',
        width: '8em',
        height: '8em',
      },
    }),
    presetRemToPx({ baseFontSize: 16 }),
  ],
  content: {
    pipeline: {
      include: [/\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/, 'src/**/*.{js,ts}'],
    },
  },
  safelist: [
    'mt-1',
    'mb-0.5',
    'text-red-600',
    'dark:text-red-400',
    'text-[11px]',
    '[line-height:1.15]',
    'i-lucide-arrow-left-right',
    'i-lucide-calendar',
    'i-lucide-list-plus',
    'i-lucide-calendar-clock',
    'i-lucide-circle-dot',
    'i-lucide-clock',
    'i-lucide-hash',
    'i-lucide-letter-text',
    'i-lucide-link-2',
    'i-lucide-list',
    'i-lucide-lock',
    'i-lucide-mail',
    'i-lucide-paperclip',
    'i-lucide-phone',
    'i-lucide-sliders-horizontal',
    'i-lucide-triangle-alert',
    'i-lucide-arrow-up-to-line',
    'i-lucide-square-check',
    'i-lucide-type',
    'i-lucide-pipette',
    'i-lucide-send-horizontal',
    'i-lucide-square-mouse-pointer',
    'i-stash:user-avatar',
    'i-lucide-group',
    'i-lucide-list-tree',
    'i-lucide-heading-1',
    'i-lucide-heading-2',
    'i-lucide-heading-3',
    'i-lucide-heading-4',
    'i-lucide-heading-5',
    'i-lucide-heading-6',
    'i-lucide-image',
    'i-lucide-trash-2',
    'i-lucide-eye',
    'i-lucide-undo-2',
    'i-lucide-redo-2',
    'i-lucide-monitor',
    'i-lucide-tablet',
    'i-lucide-smartphone',
    'i-lucide-code-xml',
    'i-lucide-more-vertical',
    'i-lucide-download',
    'i-lucide-save',
    'i-lucide-bot-message-square',
    'i-lucide-sun',
    'i-lucide-moon',
    'i-lucide-circle-help',
    'i-lucide-move-right',
    'i-lucide-credit-card',
    'i-lucide-panel-top',
    'i-lucide-table',
    'i-lucide-table-2',
    'i-lucide-x',
    'i-lucide-search',
    'i-lucide-refresh-cw',
    'i-lucide-upload',
    'i-lucide-rotate-ccw',
    'i-lucide-plus',
    'i-lucide-align-horizontal-justify-start',
    'i-lucide-rectangle-horizontal',
    'i-lucide-badge',
    '!w-[8.33%]',
    '!w-[16.67%]',
    '!w-[25%]',
    '!w-[33.33%]',
    '!w-[41.67%]',
    '!w-[50%]',
    '!w-[58.33%]',
    '!w-[66.67%]',
    '!w-[75%]',
    '!w-[83.33%]',
    '!w-[91.67%]',
    '!w-[100%]',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'col-span-7',
    'col-span-8',
    'col-span-9',
    'col-span-10',
    'col-span-11',
    'col-span-12',
  ],
  theme: {
    colors: {
      background: 'var(--background)',
      foreground: 'var(--foreground)',
      card: 'var(--card)',
      'card-foreground': 'var(--card-foreground)',
      popover: 'var(--popover)',
      'popover-foreground': 'var(--popover-foreground)',
      primary: 'var(--primary)',
      'primary-foreground': 'var(--primary-foreground)',
      secondary: 'var(--secondary)',
      'secondary-foreground': 'var(--secondary-foreground)',
      muted: 'var(--muted)',
      'muted-foreground': 'var(--muted-foreground)',
      accent: 'var(--accent)',
      'accent-foreground': 'var(--accent-foreground)',
      destructive: 'var(--destructive)',
      'destructive-foreground': 'var(--destructive-foreground)',
      border: 'var(--border)',
      'border-red': 'var(--border-red)',
      input: 'var(--input)',
      ring: 'var(--ring)',
      'chart-1': 'var(--chart-1)',
      'chart-2': 'var(--chart-2)',
      'chart-3': 'var(--chart-3)',
      'chart-4': 'var(--chart-4)',
      'chart-5': 'var(--chart-5)',
      sidebar: 'var(--sidebar)',
      'sidebar-foreground': 'var(--sidebar-foreground)',
      'sidebar-primary': 'var(--sidebar-primary)',
      'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
      'sidebar-accent': 'var(--sidebar-accent)',
      'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
      'sidebar-border': 'var(--sidebar-border)',
      'sidebar-ring': 'var(--sidebar-ring)',
    },
    borderRadius: {
      sm: 'calc(var(--radius) - 4px)',
      md: 'calc(var(--radius) - 2px)',
      lg: 'var(--radius)',
      xl: 'calc(var(--radius) + 4px)',
    },
  },
})
