import type { ElementDefinition } from '../types'
import {
  DEFAULT_DATE_TIME_VALUE_FORMAT,
  DEFAULT_DATE_VALUE_FORMAT,
  DEFAULT_TIME_VALUE_FORMAT,
} from '../constants'
import NaiveTextInput from '@/components/ui/fields/NaiveTextInput.vue'
import NaiveTextarea from '@/components/ui/fields/NaiveTextarea.vue'
import NaiveNumberInput from '@/components/ui/fields/NaiveNumberInput.vue'
import NaiveSelect from '@/components/ui/fields/NaiveSelect.vue'
import NaiveCheckboxGroup from '@/components/ui/fields/NaiveCheckboxGroup.vue'
import NaiveRadioGroup from '@/components/ui/fields/NaiveRadioGroup.vue'
import NaiveSlider from '@/components/ui/fields/NaiveSlider.vue'
import NaiveDatePicker from '@/components/ui/fields/NaiveDatePicker.vue'
import NaiveTimePicker from '@/components/ui/fields/NaiveTimePicker.vue'
import NaiveUpload from '@/components/ui/fields/NaiveUpload.vue'
import NaiveColorPicker from '@/components/ui/fields/NaiveColorPicker.vue'
import NaiveAvatar from '@/components/ui/fields/NaiveAvatar.vue'
import NaiveImage from '@/components/ui/fields/NaiveImage.vue'
import NaiveCascader from '@/components/ui/fields/NaiveCascader.vue'
import NaiveMention from '@/components/ui/fields/NaiveMention.vue'
import NaiveRate from '@/components/ui/fields/NaiveRate.vue'
import NaiveSwitch from '@/components/ui/fields/NaiveSwitch.vue'
import NaiveTreeSelect from '@/components/ui/fields/NaiveTreeSelect.vue'

const commonProps = { size: 'medium', disabled: false, clearable: true } as const

// 文本类字段共用 FormKit 组件
const textLike = (_type: string) => ({ component: NaiveTextInput, libraryName: 'NaiveTextInput' })

export const fieldElements: ElementDefinition[] = [
  {
    type: 'text',
    category: 'fields',
    icon: 'i-lucide-type',
    tooltipKey: 'fieldProps.tooltip.text',
    editor: () => import('@/components/sidebar-right/edits/editors/TextLikeEditor.vue'),
    formkit: textLike('text'),
    schema: {
      $formkit: 'text',
      nameKey: 'elements.text.name',
      labelKey: 'elements.text.label',
      outerClass: 'col-span-12',
      id: 'text_field',
      props: { ...commonProps },
      placeholderKey: 'elements.text.placeholder',
      helpKey: 'elements.common.help',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.text.description',
    },
  },
  {
    type: 'textarea',
    category: 'fields',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.textarea',
    editor: () => import('@/components/sidebar-right/edits/editors/TextLikeEditor.vue'),
    formkit: { component: NaiveTextarea, libraryName: 'NaiveTextarea' },
    schema: {
      $formkit: 'textarea',
      nameKey: 'elements.textarea.name',
      labelKey: 'elements.textarea.label',
      id: 'textarea_field',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      placeholderKey: 'elements.textarea.placeholder',
      helpKey: 'elements.common.help',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.textarea.description',
    },
  },
  {
    type: 'email',
    category: 'fields',
    icon: 'i-lucide-mail',
    tooltipKey: 'fieldProps.tooltip.email',
    editor: () => import('@/components/sidebar-right/edits/editors/TextLikeEditor.vue'),
    formkit: textLike('email'),
    schema: {
      $formkit: 'email',
      nameKey: 'elements.email.name',
      labelKey: 'elements.email.label',
      outerClass: 'col-span-12',
      id: 'email_field',
      props: { ...commonProps },
      placeholderKey: 'elements.email.placeholder',
      helpKey: 'elements.common.help',
      validation: 'email',
      validationVisibility: 'live',
      descriptionKey: 'elements.email.description',
    },
  },
  {
    type: 'number',
    category: 'fields',
    icon: 'i-lucide-hash',
    tooltipKey: 'fieldProps.tooltip.number',
    editor: () => import('@/components/sidebar-right/edits/editors/NumberEditor.vue'),
    formkit: { component: NaiveNumberInput, libraryName: 'NaiveNumberInput' },
    schema: {
      $formkit: 'number',
      nameKey: 'elements.number.name',
      labelKey: 'elements.number.label',
      outerClass: 'col-span-12',
      id: 'number_field',
      props: { ...commonProps },
      placeholderKey: 'elements.number.placeholder',
      number: 'integer',
      helpKey: 'elements.common.help',
      validation: 'number',
      validationVisibility: 'live',
      descriptionKey: 'elements.number.description',
    },
  },
  {
    type: 'url',
    category: 'fields',
    icon: 'i-lucide-link-2',
    tooltipKey: 'fieldProps.tooltip.url',
    editor: () => import('@/components/sidebar-right/edits/editors/TextLikeEditor.vue'),
    formkit: textLike('url'),
    schema: {
      $formkit: 'url',
      nameKey: 'elements.url.name',
      labelKey: 'elements.url.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      placeholderKey: 'elements.url.placeholder',
      id: 'url_field',
      validation: 'url',
      validationVisibility: 'live',
      descriptionKey: 'elements.url.description',
    },
  },
  {
    type: 'checkbox',
    category: 'fields',
    icon: 'i-lucide-square-check',
    tooltipKey: 'fieldProps.tooltip.checkbox',
    editor: () => import('@/components/sidebar-right/edits/editors/CheckboxEditor.vue'),
    formkit: { component: NaiveCheckboxGroup, libraryName: 'NaiveCheckboxGroup' },
    schema: {
      $formkit: 'checkbox',
      nameKey: 'elements.checkbox.name',
      labelKey: 'elements.checkbox.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      options: ['One'],
      id: 'checkbox_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.checkbox.description',
    },
  },
  {
    type: 'color',
    category: 'fields',
    icon: 'i-lucide-pipette',
    tooltipKey: 'fieldProps.tooltip.color',
    editor: () => import('@/components/sidebar-right/edits/editors/ColorEditor.vue'),
    formkit: { component: NaiveColorPicker, libraryName: 'NaiveColorPicker' },
    schema: {
      $formkit: 'color',
      nameKey: 'elements.color.name',
      labelKey: 'elements.color.label',
      value: '#00ff00',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      id: 'color_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.color.description',
    },
  },
  {
    type: 'date',
    category: 'fields',
    icon: 'i-lucide-calendar',
    tooltipKey: 'fieldProps.tooltip.date',
    editor: () => import('@/components/sidebar-right/edits/editors/DateLikeEditor.vue'),
    formkit: { component: NaiveDatePicker, libraryName: 'NaiveDatePicker' },
    schema: {
      $formkit: 'date',
      nameKey: 'elements.date.name',
      labelKey: 'elements.date.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps, valueFormat: DEFAULT_DATE_VALUE_FORMAT, type: 'date' },
      id: 'date_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.date.description',
    },
  },
  {
    type: 'time',
    category: 'fields',
    icon: 'i-lucide-clock',
    tooltipKey: 'fieldProps.tooltip.time',
    editor: () => import('@/components/sidebar-right/edits/editors/DateLikeEditor.vue'),
    formkit: { component: NaiveTimePicker, libraryName: 'NaiveTimePicker' },
    schema: {
      $formkit: 'time',
      nameKey: 'elements.time.name',
      labelKey: 'elements.time.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps, valueFormat: DEFAULT_TIME_VALUE_FORMAT },
      id: 'time_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.time.description',
    },
  },
  {
    type: 'naiveDateTime',
    category: 'fields',
    icon: 'i-lucide-calendar-clock',
    tooltipKey: 'fieldProps.tooltip.dateTime',
    editor: () => import('@/components/sidebar-right/edits/editors/DateTimeEditor.vue'),
    formkit: { component: NaiveDatePicker, libraryName: 'NaiveDatePicker' },
    schema: {
      $formkit: 'naiveDateTime',
      nameKey: 'elements.dateTime.name',
      labelKey: 'elements.dateTime.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: {
        ...commonProps,
        valueFormat: DEFAULT_DATE_TIME_VALUE_FORMAT,
        type: 'datetime',
      },
      id: 'date_time_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.dateTime.description',
    },
  },
  {
    type: 'file',
    category: 'fields',
    icon: 'i-lucide-paperclip',
    tooltipKey: 'fieldProps.tooltip.file',
    editor: () => import('@/components/sidebar-right/edits/editors/FileEditor.vue'),
    formkit: { component: NaiveUpload, libraryName: 'NaiveUpload' },
    schema: {
      $formkit: 'file',
      nameKey: 'elements.file.name',
      labelKey: 'elements.file.label',
      helpKey: 'elements.file.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      id: 'file_field',
      validation: '',
      accept: '.pdf,.doc,.docx,.xml,.md,.csv,.jpg,.png,.webp',
      validationVisibility: 'live',
      descriptionKey: 'elements.file.description',
    },
  },
  {
    type: 'password',
    category: 'fields',
    icon: 'i-lucide-lock',
    tooltipKey: 'fieldProps.tooltip.password',
    editor: () => import('@/components/sidebar-right/edits/editors/PasswordEditor.vue'),
    formkit: textLike('password'),
    schema: {
      $formkit: 'password',
      nameKey: 'elements.password.name',
      labelKey: 'elements.password.label',
      placeholderKey: 'elements.password.placeholder',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      id: 'password_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.password.description',
    },
  },
  {
    type: 'radio',
    category: 'fields',
    icon: 'i-lucide-circle-dot',
    tooltipKey: 'fieldProps.tooltip.radio',
    editor: () => import('@/components/sidebar-right/edits/editors/RadioEditor.vue'),
    formkit: { component: NaiveRadioGroup, libraryName: 'NaiveRadioGroup' },
    schema: {
      $formkit: 'radio',
      options: ['one'],
      nameKey: 'elements.radio.name',
      labelKey: 'elements.radio.label',
      outerClass: 'col-span-12',
      helpKey: 'elements.common.help',
      props: { ...commonProps },
      id: 'radio_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.radio.description',
    },
  },
  {
    type: 'range',
    category: 'fields',
    icon: 'i-lucide-sliders-horizontal',
    tooltipKey: 'fieldProps.tooltip.range',
    editor: () => import('@/components/sidebar-right/edits/editors/RangeEditor.vue'),
    formkit: { component: NaiveSlider, libraryName: 'NaiveSlider' },
    schema: {
      $formkit: 'range',
      nameKey: 'elements.range.name',
      labelKey: 'elements.range.label',
      children: '$slots.default',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { ...commonProps },
      value: 0,
      __raw__sectionsSchema: {
        prefix: {
          $el: 'div',
          attrs: {
            class: ' py-1 px-2 mr-1 text-sm flex items-center bg-muted mr-2 rounded-md',
          },
          children: '$value',
        },
      },
      id: 'range_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.range.description',
    },
  },
  {
    type: 'select',
    category: 'fields',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.select',
    editor: () => import('@/components/sidebar-right/edits/editors/SelectEditor.vue'),
    formkit: { component: NaiveSelect, libraryName: 'NaiveSelect' },
    schema: {
      $formkit: 'select',
      nameKey: 'elements.select.name',
      labelKey: 'elements.select.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
      },
      id: 'select_field',
      validation: '',
      validationVisibility: 'live',
      options: ['one'],
      descriptionKey: 'elements.select.description',
    },
  },
  {
    type: 'naiveCascader',
    category: 'fields',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.naiveCascader',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveCascaderEditor.vue'),
    formkit: { component: NaiveCascader, libraryName: 'NaiveCascader' },
    schema: {
      $formkit: 'naiveCascader',
      nameKey: 'elements.naiveCascader.name',
      labelKey: 'elements.naiveCascader.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
      },
      placeholderKey: 'elements.common.selectPlaceholder',
      id: 'naive_cascader_field',
      validation: '',
      validationVisibility: 'live',
      options: [
        {
          label: 'Option 1',
          value: '1',
          children: [
            { label: 'Option 1-1', value: '1-1' },
            { label: 'Option 1-2', value: '1-2' },
          ],
        },
        {
          label: 'Option 2',
          value: '2',
        },
      ],
      descriptionKey: 'elements.naiveCascader.description',
    },
  },
  {
    type: 'naiveTreeSelect',
    category: 'fields',
    icon: 'i-lucide-list-tree',
    tooltipKey: 'fieldProps.tooltip.naiveTreeSelect',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveTreeSelectEditor.vue'),
    formkit: { component: NaiveTreeSelect, libraryName: 'NaiveTreeSelect' },
    schema: {
      $formkit: 'naiveTreeSelect',
      nameKey: 'elements.naiveTreeSelect.name',
      labelKey: 'elements.naiveTreeSelect.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
      },
      placeholderKey: 'elements.common.selectPlaceholder',
      id: 'naive_tree_select_field',
      validation: '',
      validationVisibility: 'live',
      options: [
        {
          label: 'Node 1',
          key: '1',
          children: [
            { label: 'Node 1-1', key: '1-1' },
            { label: 'Node 1-2', key: '1-2' },
          ],
        },
        { label: 'Node 2', key: '2' },
      ],
      descriptionKey: 'elements.naiveTreeSelect.description',
    },
  },
  {
    type: 'naiveMention',
    category: 'fields',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.naiveMention',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveMentionEditor.vue'),
    formkit: { component: NaiveMention, libraryName: 'NaiveMention' },
    schema: {
      $formkit: 'naiveMention',
      nameKey: 'elements.naiveMention.name',
      labelKey: 'elements.naiveMention.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { size: 'medium', disabled: false },
      placeholderKey: 'elements.naiveMention.placeholder',
      id: 'naive_mention_field',
      validation: '',
      validationVisibility: 'live',
      options: ['alice', 'bob'],
      descriptionKey: 'elements.naiveMention.description',
    },
  },
  {
    type: 'naiveRate',
    category: 'fields',
    icon: 'i-lucide-sliders-horizontal',
    tooltipKey: 'fieldProps.tooltip.naiveRate',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveRateEditor.vue'),
    formkit: { component: NaiveRate, libraryName: 'NaiveRate' },
    schema: {
      $formkit: 'naiveRate',
      nameKey: 'elements.naiveRate.name',
      labelKey: 'elements.naiveRate.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { disabled: false, clearable: true, allowHalf: false, count: 5 },
      value: 0,
      id: 'naive_rate_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.naiveRate.description',
    },
  },
  {
    type: 'naiveSwitch',
    category: 'fields',
    icon: 'i-lucide-square-check',
    tooltipKey: 'fieldProps.tooltip.naiveSwitch',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveSwitchEditor.vue'),
    formkit: { component: NaiveSwitch, libraryName: 'NaiveSwitch' },
    schema: {
      $formkit: 'naiveSwitch',
      nameKey: 'elements.naiveSwitch.name',
      labelKey: 'elements.naiveSwitch.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { size: 'medium', disabled: false },
      value: false,
      id: 'naive_switch_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.naiveSwitch.description',
    },
  },
  {
    type: 'naiveAvatar',
    category: 'fields',
    icon: 'i-stash:user-avatar',
    tooltipKey: 'fieldProps.tooltip.naiveAvatar',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveAvatarEditor.vue'),
    formkit: { component: NaiveAvatar, libraryName: 'NaiveAvatar' },
    schema: {
      $formkit: 'naiveAvatar',
      nameKey: 'elements.naiveAvatar.name',
      labelKey: 'elements.naiveAvatar.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: { src: '', avatarSize: 48, round: true, bordered: false, fallbackText: 'A' },
      id: 'naive_avatar_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.naiveAvatar.description',
    },
  },
  {
    type: 'naiveImage',
    category: 'fields',
    icon: 'i-lucide-image',
    tooltipKey: 'fieldProps.tooltip.naiveImage',
    editor: () => import('@/components/sidebar-right/edits/editors/NaiveImageEditor.vue'),
    formkit: { component: NaiveImage, libraryName: 'NaiveImage' },
    schema: {
      $formkit: 'naiveImage',
      nameKey: 'elements.naiveImage.name',
      labelKey: 'elements.naiveImage.label',
      helpKey: 'elements.common.help',
      outerClass: 'col-span-12',
      props: {
        src: '',
        alt: '',
        width: 240,
        height: 160,
        objectFit: 'cover',
        previewDisabled: false,
        lazy: false,
      },
      id: 'naive_image_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.naiveImage.description',
    },
  },
  {
    type: 'tel',
    category: 'fields',
    icon: 'i-lucide-phone',
    tooltipKey: 'fieldProps.tooltip.tel',
    editor: () => import('@/components/sidebar-right/edits/editors/TextLikeEditor.vue'),
    formkit: textLike('tel'),
    schema: {
      $formkit: 'tel',
      nameKey: 'elements.tel.name',
      labelKey: 'elements.tel.label',
      placeholderKey: 'elements.tel.placeholder',
      outerClass: 'col-span-12',
      helpKey: 'elements.common.help',
      props: { ...commonProps },
      id: 'tel_field',
      validation: '',
      validationVisibility: 'live',
      descriptionKey: 'elements.tel.description',
    },
  },
]
