import type { ElementDefinition } from '../types'
import {
  DEFAULT_DATE_TIME_VALUE_FORMAT,
  DEFAULT_DATE_VALUE_FORMAT,
  DEFAULT_TIME_VALUE_FORMAT,
} from '../constants'
import { INPUT_FULL_EVENTS, INPUT_BASIC_EVENTS, DISPLAY_CLICK_EVENTS } from './bind-events'

// 纯数据目录：不 import 任何 .vue。FormKit 组件绑定在 elements/formkit.ts（按 type 索引）。
// 所有字段均以 $cmp 组件引用渲染（renderAs:'cmp'），target 为 FormKitSchema 的 $cmp 名。

// disabled 不放进公共默认值：它是 FormKit 保留的级联属性名，节点一旦显式写入
// false，就会锁死该节点不再响应表单/分组级 :disabled 级联（FormKit 只在节点自身
// 未显式设置该 prop 时才会回退到父级 config.disabled）。默认不写此键，字段就能
// 正常继承外层禁用态；编辑面板的"禁用"开关仍可按需显式打开，覆盖继承值。
const commonProps = { size: 'medium', clearable: true } as const

export const fieldElements: ElementDefinition[] = [
  {
    type: 'text',
    category: 'field',
    icon: 'i-lucide-type',
    tooltipKey: 'fieldProps.tooltip.text',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.text.name',
      labelKey: 'elements.text.label',
      props: { ...commonProps },
      placeholderKey: 'elements.text.placeholder',
      descriptionKey: 'elements.text.description',
    },
  },
  {
    type: 'textarea',
    category: 'field',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.textarea',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.textarea.name',
      labelKey: 'elements.textarea.label',
      props: { ...commonProps },
      placeholderKey: 'elements.textarea.placeholder',
      descriptionKey: 'elements.textarea.description',
    },
  },
  {
    type: 'email',
    category: 'field',
    icon: 'i-lucide-mail',
    tooltipKey: 'fieldProps.tooltip.email',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.email.name',
      labelKey: 'elements.email.label',
      props: { ...commonProps },
      placeholderKey: 'elements.email.placeholder',
      validation: 'email',
      descriptionKey: 'elements.email.description',
    },
  },
  {
    type: 'url',
    category: 'field',
    icon: 'i-lucide-link-2',
    tooltipKey: 'fieldProps.tooltip.url',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.url.name',
      labelKey: 'elements.url.label',
      props: { ...commonProps },
      placeholderKey: 'elements.url.placeholder',
      validation: 'url',
      descriptionKey: 'elements.url.description',
    },
  },
  {
    type: 'tel',
    category: 'field',
    icon: 'i-lucide-phone',
    tooltipKey: 'fieldProps.tooltip.tel',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.tel.name',
      labelKey: 'elements.tel.label',
      placeholderKey: 'elements.tel.placeholder',
      props: { ...commonProps },
      descriptionKey: 'elements.tel.description',
    },
  },
  {
    type: 'password',
    category: 'field',
    icon: 'i-lucide-lock',
    tooltipKey: 'fieldProps.tooltip.password',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.password.name',
      labelKey: 'elements.password.label',
      placeholderKey: 'elements.password.placeholder',
      props: { ...commonProps },
      descriptionKey: 'elements.password.description',
    },
  },
  {
    type: 'number',
    category: 'field',
    icon: 'i-lucide-hash',
    tooltipKey: 'fieldProps.tooltip.number',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.number.name',
      labelKey: 'elements.number.label',
      props: { ...commonProps, number: 'integer' },
      placeholderKey: 'elements.number.placeholder',
      validation: 'number',
      descriptionKey: 'elements.number.description',
    },
  },
  {
    type: 'range',
    category: 'field',
    icon: 'i-lucide-sliders-horizontal',
    tooltipKey: 'fieldProps.tooltip.range',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.range.name',
      labelKey: 'elements.range.label',
      props: {
        ...commonProps,
        children: '$slots.default',
        __raw__sectionsSchema: {
          prefix: {
            $el: 'div',
            attrs: {
              class: ' py-1 px-2 mr-1 text-sm flex items-center bg-muted mr-2 rounded-md',
            },
            children: '$value',
          },
        },
      },
      value: 0,
      descriptionKey: 'elements.range.description',
    },
  },
  {
    type: 'date',
    category: 'field',
    icon: 'i-lucide-calendar',
    tooltipKey: 'fieldProps.tooltip.date',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.date.name',
      labelKey: 'elements.date.label',
      props: { ...commonProps, valueFormat: DEFAULT_DATE_VALUE_FORMAT, pickerType: 'date' },
      descriptionKey: 'elements.date.description',
    },
  },
  {
    type: 'time',
    category: 'field',
    icon: 'i-lucide-clock',
    tooltipKey: 'fieldProps.tooltip.time',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.time.name',
      labelKey: 'elements.time.label',
      props: { ...commonProps, valueFormat: DEFAULT_TIME_VALUE_FORMAT },
      descriptionKey: 'elements.time.description',
    },
  },
  {
    type: 'naiveDateTime',
    category: 'field',
    icon: 'i-lucide-calendar-clock',
    tooltipKey: 'fieldProps.tooltip.dateTime',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.dateTime.name',
      labelKey: 'elements.dateTime.label',
      props: {
        ...commonProps,
        valueFormat: DEFAULT_DATE_TIME_VALUE_FORMAT,
        pickerType: 'datetime',
      },
      descriptionKey: 'elements.dateTime.description',
    },
  },
  {
    type: 'select',
    category: 'field',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.select',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.select.name',
      labelKey: 'elements.select.label',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: ['one'],
      },
      descriptionKey: 'elements.select.description',
    },
  },
  {
    type: 'radio',
    category: 'field',
    icon: 'i-lucide-circle-dot',
    tooltipKey: 'fieldProps.tooltip.radio',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.radio.name',
      labelKey: 'elements.radio.label',
      props: { ...commonProps, options: ['one'] },
      descriptionKey: 'elements.radio.description',
    },
  },
  {
    type: 'checkbox',
    category: 'field',
    icon: 'i-lucide-square-check',
    tooltipKey: 'fieldProps.tooltip.checkbox',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.checkbox.name',
      labelKey: 'elements.checkbox.label',
      props: { ...commonProps, options: ['One'] },
      descriptionKey: 'elements.checkbox.description',
    },
  },
  {
    type: 'naiveCascader',
    category: 'field',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.naiveCascader',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveCascader.name',
      labelKey: 'elements.naiveCascader.label',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: [
          {
            label: 'Option 1',
            value: '1',
            children: [
              { label: 'Option 1-1', value: '1-1' },
              { label: 'Option 1-2', value: '1-2' },
            ],
          },
          {
            label: 'Option 2',
            value: '2',
          },
        ],
      },
      placeholderKey: 'elements.common.selectPlaceholder',
      descriptionKey: 'elements.naiveCascader.description',
    },
  },
  {
    type: 'naiveTreeSelect',
    category: 'field',
    icon: 'i-lucide-list-tree',
    tooltipKey: 'fieldProps.tooltip.naiveTreeSelect',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveTreeSelect.name',
      labelKey: 'elements.naiveTreeSelect.label',
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: [
          {
            label: 'Node 1',
            key: '1',
            children: [
              { label: 'Node 1-1', key: '1-1' },
              { label: 'Node 1-2', key: '1-2' },
            ],
          },
          { label: 'Node 2', key: '2' },
        ],
      },
      placeholderKey: 'elements.common.selectPlaceholder',
      descriptionKey: 'elements.naiveTreeSelect.description',
    },
  },
  {
    type: 'naiveTransfer',
    category: 'field',
    icon: 'i-lucide-arrow-left-right',
    tooltipKey: 'fieldProps.tooltip.naiveTransfer',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveTransfer.name',
      labelKey: 'elements.naiveTransfer.label',
      // disabled 不显式写 false：理由同 commonProps 顶部注释——显式 false 会锁死
      // 该节点，不再响应表单/分组级联禁用
      props: {
        size: 'medium',
        filterable: false,
        options: [
          { label: 'Option 1', value: '1' },
          { label: 'Option 2', value: '2' },
          { label: 'Option 3', value: '3' },
        ],
      },
      value: [],
      descriptionKey: 'elements.naiveTransfer.description',
    },
  },
  {
    type: 'naiveMention',
    category: 'field',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.naiveMention',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveMention.name',
      labelKey: 'elements.naiveMention.label',
      // disabled 不显式写 false：理由同 commonProps 顶部注释
      props: { size: 'medium' },
      placeholderKey: 'elements.naiveMention.placeholder',
      options: ['alice', 'bob'],
      descriptionKey: 'elements.naiveMention.description',
    },
  },
  {
    type: 'naiveAutoComplete',
    category: 'field',
    icon: 'i-lucide-sparkles',
    tooltipKey: 'fieldProps.tooltip.naiveAutoComplete',
    bindEvents: INPUT_FULL_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveAutoComplete.name',
      labelKey: 'elements.naiveAutoComplete.label',
      props: { ...commonProps },
      placeholderKey: 'elements.naiveAutoComplete.placeholder',
      options: ['Apple', 'Banana'],
      descriptionKey: 'elements.naiveAutoComplete.description',
    },
  },
  {
    type: 'naiveSwitch',
    category: 'field',
    icon: 'i-lucide-square-check',
    tooltipKey: 'fieldProps.tooltip.naiveSwitch',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveSwitch.name',
      labelKey: 'elements.naiveSwitch.label',
      // disabled 不显式写 false：理由同 commonProps 顶部注释
      props: { size: 'medium' },
      value: false,
      descriptionKey: 'elements.naiveSwitch.description',
    },
  },
  {
    type: 'naiveRate',
    category: 'field',
    icon: 'i-lucide-sliders-horizontal',
    tooltipKey: 'fieldProps.tooltip.naiveRate',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveRate.name',
      labelKey: 'elements.naiveRate.label',
      // 不写 disabled 默认值，理由同 commonProps 顶部注释：留空才能继承表单/分组的
      // 级联禁用态，参见 NaiveRate.vue 里 disabled → readonly 的映射
      props: { clearable: true, allowHalf: false, count: 5 },
      value: 0,
      descriptionKey: 'elements.naiveRate.description',
    },
  },
  {
    type: 'file',
    category: 'field',
    icon: 'i-lucide-paperclip',
    tooltipKey: 'fieldProps.tooltip.file',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.file.name',
      labelKey: 'elements.file.label',
      helpKey: 'elements.file.help',
      props: { ...commonProps, accept: '.pdf,.doc,.docx,.xml,.md,.csv,.jpg,.png,.webp' },
      descriptionKey: 'elements.file.description',
    },
  },
  {
    type: 'naiveImage',
    category: 'field',
    icon: 'i-lucide-image',
    tooltipKey: 'fieldProps.tooltip.naiveImage',
    bindEvents: DISPLAY_CLICK_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveImage.name',
      labelKey: 'elements.naiveImage.label',
      props: {
        src: '',
        alt: '',
        // K2：新拖入的图片默认"按比例"自适应所在列宽（16:9），不再带固定 240×160——
        // 画布 grid 行高是 auto，固定像素宽高与所占列数无关，占 12 列时图片缩在一角，
        // 占 3 列又会溢出格子。旧数据不做兼容（仓库还没有生产使用）。
        sizeMode: 'ratio',
        aspectRatio: '16/9',
        objectFit: 'cover',
        previewDisabled: false,
        lazy: false,
      },
      descriptionKey: 'elements.naiveImage.description',
    },
  },
  {
    type: 'naiveAvatar',
    category: 'field',
    icon: 'i-stash:user-avatar',
    tooltipKey: 'fieldProps.tooltip.naiveAvatar',
    bindEvents: DISPLAY_CLICK_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.naiveAvatar.name',
      labelKey: 'elements.naiveAvatar.label',
      props: { src: '', size: 'small', round: true, bordered: false, fallbackText: 'A' },
      descriptionKey: 'elements.naiveAvatar.description',
    },
  },
  {
    type: 'color',
    category: 'field',
    icon: 'i-lucide-pipette',
    tooltipKey: 'fieldProps.tooltip.color',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.color.name',
      labelKey: 'elements.color.label',
      value: '#00ff00',
      props: { ...commonProps },
      descriptionKey: 'elements.color.description',
    },
  },
  {
    type: 'richText',
    category: 'field',
    icon: 'i-lucide-file-text',
    tooltipKey: 'fieldProps.tooltip.richText',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.richText.name',
      labelKey: 'elements.richText.label',
      // toolbar 默认全开（RICH_TEXT_TOOLBAR_ITEMS 的字面量列表见
      // components/ui/fields/rich-text-toolbar.ts，此处不引入 .vue 目录不能 import 它，
      // 直接照抄同一份 key，两处顺序/拼写必须保持一致）
      props: {
        minHeight: 160,
        maxLength: null,
        toolbar: [
          'bold',
          'italic',
          'underline',
          'strike',
          'heading',
          'bulletList',
          'orderedList',
          'blockquote',
          'link',
          'clear',
          'undo',
          'redo',
        ],
      },
      placeholderKey: 'elements.richText.placeholder',
      value: '',
      descriptionKey: 'elements.richText.description',
    },
  },
  {
    type: 'signature',
    category: 'field',
    icon: 'i-lucide-signature',
    tooltipKey: 'fieldProps.tooltip.signature',
    bindEvents: INPUT_BASIC_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.signature.name',
      labelKey: 'elements.signature.label',
      props: { height: 180, strokeColor: '#111111', strokeWidth: 2 },
      value: '',
      descriptionKey: 'elements.signature.description',
    },
  },
]
