import type { ElementDefinition } from "../types";
import {
  DEFAULT_DATE_TIME_VALUE_FORMAT,
  DEFAULT_DATE_VALUE_FORMAT,
  DEFAULT_TIME_VALUE_FORMAT,
} from "../constants";

// 纯数据目录：不 import 任何 .vue。FormKit 组件绑定在 elements/formkit.ts（按 type 索引）。
// 所有字段均以 $cmp 组件引用渲染（renderAs:'cmp'），target 为 FormKitSchema 的 $cmp 名。

const commonProps = { size: "medium", disabled: false, clearable: true } as const;

export const fieldElements: ElementDefinition[] = [
  {
    type: "text",
    category: "field",
    icon: "i-lucide-type",
    tooltipKey: "fieldProps.tooltip.text",
    editor: () => import("@/components/sidebar-right/edits/editors/TextLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.text.name",
      labelKey: "elements.text.label",
      outerClass: "col-span-12",
      props: { ...commonProps },
      placeholderKey: "elements.text.placeholder",
      helpKey: "elements.common.help",
      descriptionKey: "elements.text.description",
    },
  },
  {
    type: "textarea",
    category: "field",
    icon: "i-lucide-letter-text",
    tooltipKey: "fieldProps.tooltip.textarea",
    editor: () => import("@/components/sidebar-right/edits/editors/TextLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.textarea.name",
      labelKey: "elements.textarea.label",
      outerClass: "col-span-12",
      props: { ...commonProps },
      placeholderKey: "elements.textarea.placeholder",
      helpKey: "elements.common.help",
      descriptionKey: "elements.textarea.description",
    },
  },
  {
    type: "email",
    category: "field",
    icon: "i-lucide-mail",
    tooltipKey: "fieldProps.tooltip.email",
    editor: () => import("@/components/sidebar-right/edits/editors/TextLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.email.name",
      labelKey: "elements.email.label",
      outerClass: "col-span-12",
      props: { ...commonProps },
      placeholderKey: "elements.email.placeholder",
      helpKey: "elements.common.help",
      validation: "email",
      descriptionKey: "elements.email.description",
    },
  },
  {
    type: "number",
    category: "field",
    icon: "i-lucide-hash",
    tooltipKey: "fieldProps.tooltip.number",
    editor: () => import("@/components/sidebar-right/edits/editors/NumberEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.number.name",
      labelKey: "elements.number.label",
      outerClass: "col-span-12",
      props: { ...commonProps, number: "integer" },
      placeholderKey: "elements.number.placeholder",
      helpKey: "elements.common.help",
      validation: "number",
      descriptionKey: "elements.number.description",
    },
  },
  {
    type: "url",
    category: "field",
    icon: "i-lucide-link-2",
    tooltipKey: "fieldProps.tooltip.url",
    editor: () => import("@/components/sidebar-right/edits/editors/TextLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.url.name",
      labelKey: "elements.url.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps },
      placeholderKey: "elements.url.placeholder",
      validation: "url",
      descriptionKey: "elements.url.description",
    },
  },
  {
    type: "checkbox",
    category: "field",
    icon: "i-lucide-square-check",
    tooltipKey: "fieldProps.tooltip.checkbox",
    editor: () => import("@/components/sidebar-right/edits/editors/CheckboxEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.checkbox.name",
      labelKey: "elements.checkbox.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps, options: ["One"] },
      descriptionKey: "elements.checkbox.description",
    },
  },
  {
    type: "color",
    category: "field",
    icon: "i-lucide-pipette",
    tooltipKey: "fieldProps.tooltip.color",
    editor: () => import("@/components/sidebar-right/edits/editors/ColorEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.color.name",
      labelKey: "elements.color.label",
      value: "#00ff00",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps },
      descriptionKey: "elements.color.description",
    },
  },
  {
    type: "date",
    category: "field",
    icon: "i-lucide-calendar",
    tooltipKey: "fieldProps.tooltip.date",
    editor: () => import("@/components/sidebar-right/edits/editors/DateLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.date.name",
      labelKey: "elements.date.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps, valueFormat: DEFAULT_DATE_VALUE_FORMAT, type: "date" },
      descriptionKey: "elements.date.description",
    },
  },
  {
    type: "time",
    category: "field",
    icon: "i-lucide-clock",
    tooltipKey: "fieldProps.tooltip.time",
    editor: () => import("@/components/sidebar-right/edits/editors/DateLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.time.name",
      labelKey: "elements.time.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps, valueFormat: DEFAULT_TIME_VALUE_FORMAT },
      descriptionKey: "elements.time.description",
    },
  },
  {
    type: "naiveDateTime",
    category: "field",
    icon: "i-lucide-calendar-clock",
    tooltipKey: "fieldProps.tooltip.dateTime",
    editor: () => import("@/components/sidebar-right/edits/editors/DateTimeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.dateTime.name",
      labelKey: "elements.dateTime.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        ...commonProps,
        valueFormat: DEFAULT_DATE_TIME_VALUE_FORMAT,
        type: "datetime",
      },
      descriptionKey: "elements.dateTime.description",
    },
  },
  {
    type: "file",
    category: "field",
    icon: "i-lucide-paperclip",
    tooltipKey: "fieldProps.tooltip.file",
    editor: () => import("@/components/sidebar-right/edits/editors/FileEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.file.name",
      labelKey: "elements.file.label",
      helpKey: "elements.file.help",
      outerClass: "col-span-12",
      props: { ...commonProps, accept: ".pdf,.doc,.docx,.xml,.md,.csv,.jpg,.png,.webp" },
      descriptionKey: "elements.file.description",
    },
  },
  {
    type: "password",
    category: "field",
    icon: "i-lucide-lock",
    tooltipKey: "fieldProps.tooltip.password",
    editor: () => import("@/components/sidebar-right/edits/editors/PasswordEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.password.name",
      labelKey: "elements.password.label",
      placeholderKey: "elements.password.placeholder",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { ...commonProps },
      descriptionKey: "elements.password.description",
    },
  },
  {
    type: "radio",
    category: "field",
    icon: "i-lucide-circle-dot",
    tooltipKey: "fieldProps.tooltip.radio",
    editor: () => import("@/components/sidebar-right/edits/editors/RadioEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.radio.name",
      labelKey: "elements.radio.label",
      outerClass: "col-span-12",
      helpKey: "elements.common.help",
      props: { ...commonProps, options: ["one"] },
      descriptionKey: "elements.radio.description",
    },
  },
  {
    type: "range",
    category: "field",
    icon: "i-lucide-sliders-horizontal",
    tooltipKey: "fieldProps.tooltip.range",
    editor: () => import("@/components/sidebar-right/edits/editors/RangeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.range.name",
      labelKey: "elements.range.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        ...commonProps,
        children: "$slots.default",
        __raw__sectionsSchema: {
          prefix: {
            $el: "div",
            attrs: {
              class: " py-1 px-2 mr-1 text-sm flex items-center bg-muted mr-2 rounded-md",
            },
            children: "$value",
          },
        },
      },
      value: 0,
      descriptionKey: "elements.range.description",
    },
  },
  {
    type: "select",
    category: "field",
    icon: "i-lucide-list",
    tooltipKey: "fieldProps.tooltip.select",
    editor: () => import("@/components/sidebar-right/edits/editors/SelectEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.select.name",
      labelKey: "elements.select.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: ["one"],
      },
      descriptionKey: "elements.select.description",
    },
  },
  {
    type: "naiveCascader",
    category: "field",
    icon: "i-lucide-list",
    tooltipKey: "fieldProps.tooltip.naiveCascader",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveCascaderEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveCascader.name",
      labelKey: "elements.naiveCascader.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: [
          {
            label: "Option 1",
            value: "1",
            children: [
              { label: "Option 1-1", value: "1-1" },
              { label: "Option 1-2", value: "1-2" },
            ],
          },
          {
            label: "Option 2",
            value: "2",
          },
        ],
      },
      placeholderKey: "elements.common.selectPlaceholder",
      descriptionKey: "elements.naiveCascader.description",
    },
  },
  {
    type: "naiveTreeSelect",
    category: "field",
    icon: "i-lucide-list-tree",
    tooltipKey: "fieldProps.tooltip.naiveTreeSelect",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveTreeSelectEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveTreeSelect.name",
      labelKey: "elements.naiveTreeSelect.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        ...commonProps,
        filterable: false,
        multiple: false,
        options: [
          {
            label: "Node 1",
            key: "1",
            children: [
              { label: "Node 1-1", key: "1-1" },
              { label: "Node 1-2", key: "1-2" },
            ],
          },
          { label: "Node 2", key: "2" },
        ],
      },
      placeholderKey: "elements.common.selectPlaceholder",
      descriptionKey: "elements.naiveTreeSelect.description",
    },
  },
  {
    type: "naiveMention",
    category: "field",
    icon: "i-lucide-letter-text",
    tooltipKey: "fieldProps.tooltip.naiveMention",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveMentionEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveMention.name",
      labelKey: "elements.naiveMention.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { size: "medium", disabled: false },
      placeholderKey: "elements.naiveMention.placeholder",
      options: ["alice", "bob"],
      descriptionKey: "elements.naiveMention.description",
    },
  },
  {
    type: "naiveRate",
    category: "field",
    icon: "i-lucide-sliders-horizontal",
    tooltipKey: "fieldProps.tooltip.naiveRate",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveRateEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveRate.name",
      labelKey: "elements.naiveRate.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { disabled: false, clearable: true, allowHalf: false, count: 5 },
      value: 0,
      descriptionKey: "elements.naiveRate.description",
    },
  },
  {
    type: "naiveSwitch",
    category: "field",
    icon: "i-lucide-square-check",
    tooltipKey: "fieldProps.tooltip.naiveSwitch",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveSwitchEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveSwitch.name",
      labelKey: "elements.naiveSwitch.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { size: "medium", disabled: false },
      value: false,
      descriptionKey: "elements.naiveSwitch.description",
    },
  },
  {
    type: "naiveAvatar",
    category: "field",
    icon: "i-stash:user-avatar",
    tooltipKey: "fieldProps.tooltip.naiveAvatar",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveAvatarEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveAvatar.name",
      labelKey: "elements.naiveAvatar.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: { src: "", avatarSize: 48, round: true, bordered: false, fallbackText: "A" },
      descriptionKey: "elements.naiveAvatar.description",
    },
  },
  {
    type: "naiveImage",
    category: "field",
    icon: "i-lucide-image",
    tooltipKey: "fieldProps.tooltip.naiveImage",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveImageEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.naiveImage.name",
      labelKey: "elements.naiveImage.label",
      helpKey: "elements.common.help",
      outerClass: "col-span-12",
      props: {
        src: "",
        alt: "",
        width: 240,
        height: 160,
        objectFit: "cover",
        previewDisabled: false,
        lazy: false,
      },
      descriptionKey: "elements.naiveImage.description",
    },
  },
  {
    type: "tel",
    category: "field",
    icon: "i-lucide-phone",
    tooltipKey: "fieldProps.tooltip.tel",
    editor: () => import("@/components/sidebar-right/edits/editors/TextLikeEditor.vue"),
    schema: {
      renderAs: "cmp",
      nameKey: "elements.tel.name",
      labelKey: "elements.tel.label",
      placeholderKey: "elements.tel.placeholder",
      outerClass: "col-span-12",
      helpKey: "elements.common.help",
      props: { ...commonProps },
      descriptionKey: "elements.tel.description",
    },
  },
];
