import type { ElementDefinition } from '../types'
import { NO_EVENTS, BUTTON_EVENTS } from './bind-events'

// 纯数据目录：不 import 任何 .vue。FormKit 组件绑定在 elements/formkit.ts（按 type 索引）。
// 按钮类配置已展平进 props。右侧属性面板的编辑器组件（.editor）不在这里声明，见
// elements/definitions/editor-bindings.ts 顶部的说明。

// 标题类静态元素（naiveH1 ~ naiveH6 共用 NaiveTypographyHeader 组件绑定）
const heading = (depth: number, icon: string, tooltipKey: string): ElementDefinition => ({
  type: `naiveH${depth}`,
  category: 'static',
  icon,
  tooltipKey,
  bindEvents: NO_EVENTS,
  schema: {
    renderAs: 'cmp',
    props: { text: 'text' },
    nameKey: `elements.naiveH${depth}.name`,
    descriptionKey: `elements.naiveH${depth}.description`,
  },
})

export const staticElements: ElementDefinition[] = [
  {
    type: 'submit',
    category: 'static',
    icon: 'i-lucide-send-horizontal',
    tooltipKey: 'fieldProps.tooltip.submit',
    bindEvents: BUTTON_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.submit.name',
      descriptionKey: 'elements.submit.description',
      labelKey: 'elements.submit.label',
      props: {
        buttonType: 'success',
        block: true,
      },
    },
  },
  {
    type: 'reset',
    category: 'static',
    icon: 'i-lucide-rotate-ccw',
    tooltipKey: 'fieldProps.tooltip.reset',
    bindEvents: BUTTON_EVENTS,
    schema: {
      renderAs: 'cmp',
      nameKey: 'elements.reset.name',
      descriptionKey: 'elements.reset.description',
      labelKey: 'elements.reset.label',
      props: {
        buttonType: 'warning',
        block: true,
      },
    },
  },
  {
    type: 'naiveButton',
    category: 'static',
    icon: 'i-lucide-square-mouse-pointer',
    tooltipKey: 'fieldProps.tooltip.naiveButton',
    bindEvents: BUTTON_EVENTS,
    schema: {
      renderAs: 'cmp',
      // disabled 不显式写 false：它是 FormKit 保留的级联属性名，节点一旦显式写入
      // false 就会锁死不再响应表单/分组级联禁用（理由同 fields.ts 的 commonProps 注释）
      props: {
        block: true,
        bordered: true,
        circle: false,
        dashed: false,
        focusable: true,
        fullWidth: false,
        align: 'left',
        ghost: false,
        round: false,
        secondary: false,
        size: 'medium',
        buttonType: 'default',
      },
      nameKey: 'elements.naiveButton.name',
      descriptionKey: 'elements.naiveButton.description',
      labelKey: 'elements.naiveButton.label',
    },
  },
  {
    type: 'naiveText',
    category: 'static',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.naiveText',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        text: 'text',
        theme: 'default',
        depth: 1,
        strong: false,
        italic: false,
        underline: false,
        delete: false,
        code: false,
      },
      nameKey: 'elements.naiveText.name',
      descriptionKey: 'elements.naiveText.description',
    },
  },
  {
    type: 'naiveP',
    category: 'static',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.naiveP',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        theme: 'default',
        depth: 1,
        align: 'start',
        text: 'text',
      },
      nameKey: 'elements.naiveP.name',
      descriptionKey: 'elements.naiveP.description',
    },
  },
  {
    type: 'naiveA',
    category: 'static',
    icon: 'i-lucide-link-2',
    tooltipKey: 'fieldProps.tooltip.naiveA',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        text: 'text',
        href: 'https://www.example.com',
        target: '_blank',
      },
      nameKey: 'elements.naiveA.name',
      descriptionKey: 'elements.naiveA.description',
    },
  },
  {
    type: 'naiveBlockquote',
    category: 'static',
    icon: 'i-lucide-letter-text',
    tooltipKey: 'fieldProps.tooltip.naiveBlockquote',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        text: 'text',
      },
      nameKey: 'elements.naiveBlockquote.name',
      descriptionKey: 'elements.naiveBlockquote.description',
    },
  },
  heading(1, 'i-lucide-heading-1', 'fieldProps.tooltip.naiveH1'),
  heading(2, 'i-lucide-heading-2', 'fieldProps.tooltip.naiveH2'),
  heading(3, 'i-lucide-heading-3', 'fieldProps.tooltip.naiveH3'),
  heading(4, 'i-lucide-heading-4', 'fieldProps.tooltip.naiveH4'),
  heading(5, 'i-lucide-heading-5', 'fieldProps.tooltip.naiveH5'),
  heading(6, 'i-lucide-heading-6', 'fieldProps.tooltip.naiveH6'),
  {
    type: 'naiveUl',
    category: 'static',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.naiveUl',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      options: ['Item 1', 'Item 2', 'Item 3'],
      nameKey: 'elements.naiveUl.name',
      descriptionKey: 'elements.naiveUl.description',
    },
  },
  {
    type: 'naiveOl',
    category: 'static',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.naiveOl',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      options: ['Item 1', 'Item 2', 'Item 3'],
      nameKey: 'elements.naiveOl.name',
      descriptionKey: 'elements.naiveOl.description',
    },
  },
  {
    type: 'naiveLi',
    category: 'static',
    icon: 'i-lucide-list',
    tooltipKey: 'fieldProps.tooltip.naiveLi',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      value: 'List Item',
      nameKey: 'elements.naiveLi.name',
      descriptionKey: 'elements.naiveLi.description',
    },
  },
  {
    type: 'naiveDivider',
    category: 'static',
    icon: 'i-lucide-sliders-horizontal',
    tooltipKey: 'fieldProps.tooltip.naiveDivider',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        title: 'Divider',
        titlePlacement: 'center',
        dashed: false,
        vertical: false,
      },
      nameKey: 'elements.naiveDivider.name',
      descriptionKey: 'elements.naiveDivider.description',
    },
  },
  {
    type: 'naiveAlert',
    category: 'static',
    icon: 'i-lucide-triangle-alert',
    tooltipKey: 'fieldProps.tooltip.naiveAlert',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        title: 'Title',
        content: 'Alert',
        theme: 'default',
        closable: false,
        bordered: false,
        showIcon: true,
      },
      nameKey: 'elements.naiveAlert.name',
      labelKey: 'elements.naiveAlert.label',
      descriptionKey: 'elements.naiveAlert.description',
    },
  },
  {
    type: 'naiveBackTop',
    category: 'static',
    icon: 'i-lucide-arrow-up-to-line',
    tooltipKey: 'fieldProps.tooltip.naiveBackTop',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        show: true,
        right: 40,
        bottom: 40,
        visibilityHeight: 0,
      },
      nameKey: 'elements.naiveBackTop.name',
      descriptionKey: 'elements.naiveBackTop.description',
    },
  },
  {
    type: 'naiveQrCode',
    category: 'static',
    icon: 'i-lucide-qr-code',
    tooltipKey: 'fieldProps.tooltip.naiveQrCode',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      value: 'https://github.com/zeng-alt/formkit-form-builder',
      props: {
        size: 128,
        color: '#000000',
        backgroundColor: '#ffffff',
        padding: 10,
        errorCorrectionLevel: 'M',
      },
      nameKey: 'elements.naiveQrCode.name',
      descriptionKey: 'elements.naiveQrCode.description',
    },
  },
  {
    type: 'naiveProgress',
    category: 'static',
    icon: 'i-lucide-gauge',
    tooltipKey: 'fieldProps.tooltip.naiveProgress',
    bindEvents: NO_EVENTS,
    schema: {
      renderAs: 'cmp',
      props: {
        percentage: 60,
        progressType: 'line',
        status: 'default',
        processing: false,
        showIndicator: true,
        height: 8,
        strokeWidth: 6,
      },
      nameKey: 'elements.naiveProgress.name',
      descriptionKey: 'elements.naiveProgress.description',
    },
  },
]
