import type { Component } from "vue";
import type { ElementDefinition } from "../types";

// 纯数据目录：不 import 任何 .vue。FormKit 组件绑定在 elements/formkit.ts（按 type 索引）。
// 按钮类按钮配置已展平进 props（原 buttonProps 嵌套废除）。

// 标题类静态元素（naiveH1 ~ naiveH6 共用 NaiveTypographyHeader 组件绑定）
// editor 用静态 import() 便于库构建时内联进单一产物
const heading = (
  depth: number,
  icon: string,
  tooltipKey: string,
  editor: () => Promise<{ default: Component }>,
): ElementDefinition => ({
  type: `naiveH${depth}`,
  category: "static",
  icon,
  tooltipKey,
  editor,
  schema: {
    renderAs: "cmp",
    outerClass: "col-span-12",
    props: { text: "text" },
    nameKey: `elements.naiveH${depth}.name`,
    descriptionKey: `elements.naiveH${depth}.description`,
  },
});

export const staticElements: ElementDefinition[] = [
  {
    type: "submit",
    category: "static",
    icon: "i-lucide-send-horizontal",
    tooltipKey: "fieldProps.tooltip.submit",
    editor: () => import("@/components/sidebar-right/edits/editors/SubmitEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12 pt-2",
      nameKey: "elements.submit.name",
      descriptionKey: "elements.submit.description",
      labelKey: "elements.submit.label",
      props: {
        buttonType: "default",
      },
    },
  },
  {
    type: "reset",
    category: "static",
    icon: "i-lucide-rotate-ccw",
    tooltipKey: "fieldProps.tooltip.reset",
    editor: () => import("@/components/sidebar-right/edits/editors/SubmitEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12 pt-2",
      nameKey: "elements.reset.name",
      descriptionKey: "elements.reset.description",
      labelKey: "elements.reset.label",
      props: {
        buttonType: "error",
      },
    },
  },
  {
    type: "naiveButton",
    category: "static",
    icon: "i-lucide-square-mouse-pointer",
    tooltipKey: "fieldProps.tooltip.naiveButton",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveButtonEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12 pt-2",
      props: {
        block: false,
        bordered: true,
        circle: false,
        dashed: false,
        disabled: false,
        focusable: true,
        fullWidth: false,
        align: "left",
        ghost: false,
        round: false,
        secondary: false,
        size: "medium",
        buttonType: "default",
      },
      nameKey: "elements.naiveButton.name",
      descriptionKey: "elements.naiveButton.description",
      labelKey: "elements.naiveButton.label",
    },
  },
  {
    type: "naiveText",
    category: "static",
    icon: "i-lucide-letter-text",
    tooltipKey: "fieldProps.tooltip.naiveText",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveTextEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        text: "text",
        theme: "default",
        depth: 1,
        strong: false,
        italic: false,
        underline: false,
        delete: false,
        code: false,
      },
      nameKey: "elements.naiveText.name",
      descriptionKey: "elements.naiveText.description",
    },
  },
  {
    type: "naiveP",
    category: "static",
    icon: "i-lucide-letter-text",
    tooltipKey: "fieldProps.tooltip.naiveP",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveParagraphEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        theme: "default",
        depth: 1,
        align: "start",
        text: "text",
      },
      nameKey: "elements.naiveP.name",
      descriptionKey: "elements.naiveP.description",
    },
  },
  {
    type: "naiveA",
    category: "static",
    icon: "i-lucide-link-2",
    tooltipKey: "fieldProps.tooltip.naiveA",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveLinkEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        text: "text",
        href: "https://www.example.com",
        target: "_blank",
      },
      nameKey: "elements.naiveA.name",
      descriptionKey: "elements.naiveA.description",
    },
  },
  {
    type: "naiveBlockquote",
    category: "static",
    icon: "i-lucide-letter-text",
    tooltipKey: "fieldProps.tooltip.naiveBlockquote",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveBlockquoteEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        text: "text",
      },
      nameKey: "elements.naiveBlockquote.name",
      descriptionKey: "elements.naiveBlockquote.description",
    },
  },
  heading(
    1,
    "i-lucide-heading-1",
    "fieldProps.tooltip.naiveH1",
    () => import("@/components/sidebar-right/edits/editors/NaiveH1Editor.vue"),
  ),
  heading(
    2,
    "i-lucide-heading-2",
    "fieldProps.tooltip.naiveH2",
    () => import("@/components/sidebar-right/edits/editors/NaiveH2Editor.vue"),
  ),
  heading(
    3,
    "i-lucide-heading-3",
    "fieldProps.tooltip.naiveH3",
    () => import("@/components/sidebar-right/edits/editors/NaiveH3Editor.vue"),
  ),
  heading(
    4,
    "i-lucide-heading-4",
    "fieldProps.tooltip.naiveH4",
    () => import("@/components/sidebar-right/edits/editors/NaiveH4Editor.vue"),
  ),
  heading(
    5,
    "i-lucide-heading-5",
    "fieldProps.tooltip.naiveH5",
    () => import("@/components/sidebar-right/edits/editors/NaiveH5Editor.vue"),
  ),
  heading(
    6,
    "i-lucide-heading-6",
    "fieldProps.tooltip.naiveH6",
    () => import("@/components/sidebar-right/edits/editors/NaiveH6Editor.vue"),
  ),
  {
    type: "naiveUl",
    category: "static",
    icon: "i-lucide-list",
    tooltipKey: "fieldProps.tooltip.naiveUl",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveUlEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      options: ["Item 1", "Item 2", "Item 3"],
      nameKey: "elements.naiveUl.name",
      descriptionKey: "elements.naiveUl.description",
    },
  },
  {
    type: "naiveOl",
    category: "static",
    icon: "i-lucide-list",
    tooltipKey: "fieldProps.tooltip.naiveOl",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveOlEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      options: ["Item 1", "Item 2", "Item 3"],
      nameKey: "elements.naiveOl.name",
      descriptionKey: "elements.naiveOl.description",
    },
  },
  {
    type: "naiveLi",
    category: "static",
    icon: "i-lucide-list",
    tooltipKey: "fieldProps.tooltip.naiveLi",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveLiEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      value: "List Item",
      nameKey: "elements.naiveLi.name",
      descriptionKey: "elements.naiveLi.description",
    },
  },
  {
    type: "naiveDivider",
    category: "static",
    icon: "i-lucide-sliders-horizontal",
    tooltipKey: "fieldProps.tooltip.naiveDivider",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveDividerEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        title: "Divider",
        titlePlacement: "center",
        dashed: false,
        vertical: false,
      },
      nameKey: "elements.naiveDivider.name",
      descriptionKey: "elements.naiveDivider.description",
    },
  },
  {
    type: "naiveAlert",
    category: "static",
    icon: "i-lucide-triangle-alert",
    tooltipKey: "fieldProps.tooltip.naiveAlert",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveAlertEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        title: "Title",
        content: "Alert",
        theme: "default",
        closable: false,
        bordered: false,
        showIcon: true,
      },
      nameKey: "elements.naiveAlert.name",
      labelKey: "elements.naiveAlert.label",
      descriptionKey: "elements.naiveAlert.description",
    },
  },
  {
    type: "naiveBackTop",
    category: "static",
    icon: "i-lucide-arrow-up-to-line",
    tooltipKey: "fieldProps.tooltip.naiveBackTop",
    editor: () => import("@/components/sidebar-right/edits/editors/NaiveBackTopEditor.vue"),
    schema: {
      renderAs: "cmp",
      outerClass: "col-span-12",
      props: {
        show: true,
        right: 40,
        bottom: 40,
        visibilityHeight: 0,
      },
      nameKey: "elements.naiveBackTop.name",
      descriptionKey: "elements.naiveBackTop.description",
    },
  },
];
