import type { FormKitSchemaFormKit } from '@formkit/core'
import { ref } from 'vue'

export const formSchema = ref<FormKitSchemaFormKit[]>([
  {
    $formkit: 'submit',
    outerClass: 'col-span-12 pt-2',
    type: 'submit',
    name: 'submit_button',
    label: 'Submit',
  },
])
export const selectedIndex = ref(0)

export const defaultFormElements: FormKitSchemaFormKit[] = [
  {
    $formkit: 'text',
    name: 'Text',
    label: 'Client Name',
    outerClass: 'col-span-12',
    id: 'text_field',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    placeholder: 'Enter your name',
    help: 'This is help text',
    validation: '',
    validationVisibility: 'live',
    description: 'Single line text field',
  },
  {
    $formkit: 'textarea',
    name: 'Text Area',
    label: 'Client Address',
    id: 'textarea_field',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    placeholder: 'Enter your address',
    help: 'This is help text',
    validation: '',
    validationVisibility: 'live',
    description: 'Multi-line text field',
  },
  {
    $formkit: 'email',
    name: 'Email',
    label: 'Client Email',
    outerClass: 'col-span-12',
    id: 'email_field',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    placeholder: 'Enter your email',
    help: 'This is help text',
    validation: 'email',
    validationVisibility: 'live',
    description: 'Email field input',
  },
  {
    $formkit: 'number',
    name: 'Number',
    label: 'Client Age',
    outerClass: 'col-span-12',
    id: 'number_field',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    placeholder: 'Enter your age',
    number: 'integer',
    help: 'This is help text',
    validation: 'number',
    validationVisibility: 'live',
    description: 'Single number input',
  },
  {
    $formkit: 'url',
    label: 'URL Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    placeholder: 'https://www.example.com',
    name: 'URL',
    id: 'url_field',
    validation: 'url',
    validationVisibility: 'live',
    description: 'URL field input',
  },
  {
    $formkit: 'checkbox',
    label: 'Label For Checkbox',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Checkbox',
    options: ['One'],
    id: 'checkbox_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Multiple choice checkbox',
  },
  {
    $formkit: 'color',
    label: 'Color Field',
    value: '#00ff00',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Color',
    id: 'color_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Color picker',
  },
  {
    $formkit: 'date',
    label: 'Date Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Date',
    id: 'date_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Date input picker',
  },
  {
    $formkit: 'time',
    label: 'Time Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Time',
    id: 'time_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Time input picker',
  },
  {
    $formkit: 'datetime-local',
    label: 'Date Time Local Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Date-Time',
    id: 'datetime_local_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Date and time input',
  },
  {
    $formkit: 'date-time',
    label: 'Date Time Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true, valueFormat: 'yyyy.MM.dd HH:mm:ss' },
    name: 'Date-Time',
    id: 'date_time_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Date and time input',
  },
  {
    $formkit: 'file',
    label: 'File Field',
    help: 'Accepts .pdf, .doc, .docx, .xml, .md, .csv, .jpg, .png, .webp',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'File Picker',
    id: 'file_field',
    validation: '',
    accept: '.pdf,.doc,.docx,.xml,.md,.csv,.jpg,.png,.webp',
    validationVisibility: 'live',
    description: 'One or more file uploads',
  },
  {
    $formkit: 'password',
    label: 'Password Field',
    placeholder: 'Enter your password',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Password',
    id: 'password_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Password masked field',
  },
  {
    $formkit: 'radio',
    options: ['one'],
    label: 'Radio Field',
    outerClass: 'col-span-12',
    help: 'This is help text',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Radio',
    id: 'radio_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Single choice select',
  },
  {
    $formkit: 'range',
    label: 'Range Field',
    children: '$slots.default',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    value: 0,
    name: 'Range',
    __raw__sectionsSchema: {
      prefix: {
        $el: 'div',
        attrs: {
          class: ' py-1 px-2 mr-1 text-sm flex items-center bg-muted mr-2 rounded-md',
        },
        children: '$value',
      },
    },
    id: 'range_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Slider field input',
  },
  {
    $formkit: 'select',
    label: 'Select Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: {
      size: 'medium',
      disabled: false,
      clearable: true,
      filterable: false,
      multiple: false,
    },
    name: 'Dropdown Select',
    id: 'select_field',
    validation: '',
    validationVisibility: 'live',
    options: ['one'],
    description: 'Selection dropdown',
  },
  {
    $formkit: 'naiveCascader',
    label: 'Cascader Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: {
      size: 'medium',
      disabled: false,
      clearable: true,
      filterable: false,
      multiple: false,
    },
    placeholder: 'Select...',
    name: 'Naive Cascader',
    id: 'naive_cascader_field',
    validation: '',
    validationVisibility: 'live',
    options: [
      {
        label: 'Option 1',
        value: '1',
        children: [
          { label: 'Option 1-1', value: '1-1' },
          { label: 'Option 1-2', value: '1-2' },
        ],
      },
      {
        label: 'Option 2',
        value: '2',
      },
    ],
    description: 'Cascader selection',
  },
  {
    $formkit: 'naiveTreeSelect',
    label: 'Tree Select Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: {
      size: 'medium',
      disabled: false,
      clearable: true,
      filterable: false,
      multiple: false,
    },
    placeholder: 'Select...',
    name: 'Naive Tree Select',
    id: 'naive_tree_select_field',
    validation: '',
    validationVisibility: 'live',
    options: [
      {
        label: 'Node 1',
        key: '1',
        children: [
          { label: 'Node 1-1', key: '1-1' },
          { label: 'Node 1-2', key: '1-2' },
        ],
      },
      { label: 'Node 2', key: '2' },
    ],
    description: 'Tree selection',
  },
  {
    $formkit: 'naiveMention',
    label: 'Mention Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false },
    placeholder: 'Type @ to mention',
    name: 'Naive Mention',
    id: 'naive_mention_field',
    validation: '',
    validationVisibility: 'live',
    options: ['alice', 'bob'],
    description: 'Mention input',
  },
  {
    $formkit: 'naiveRate',
    label: 'Rate Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { disabled: false, clearable: true, allowHalf: false, count: 5 },
    value: 0,
    name: 'Naive Rate',
    id: 'naive_rate_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Rating input',
  },
  {
    $formkit: 'naiveSwitch',
    label: 'Switch Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false },
    value: false,
    name: 'Naive Switch',
    id: 'naive_switch_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Boolean switch',
  },
  {
    $formkit: 'naiveCheckbox',
    label: 'Checkbox Field',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { size: 'medium', disabled: false },
    value: false,
    name: 'Naive Checkbox',
    id: 'naive_checkbox_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Boolean checkbox',
  },
  {
    $formkit: 'naiveAvatar',
    label: 'Avatar',
    help: 'This is help text',
    outerClass: 'col-span-12',
    naiveProps: { src: '', avatarSize: 48, round: true, bordered: false, fallbackText: 'A' },
    name: 'Naive Avatar',
    id: 'naive_avatar_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Avatar display',
  },
  {
    $formkit: 'tel',
    label: 'Tel Field',
    placeholder: '(+XX) XXXXXXXXXX',
    outerClass: 'col-span-12',
    help: 'This is help text',
    naiveProps: { size: 'medium', disabled: false, clearable: true },
    name: 'Telephone Number',
    id: 'tel_field',
    validation: '',
    validationVisibility: 'live',
    description: 'Telephone input field',
  },
  {
    $formkit: 'naiveButton',
    outerClass: 'col-span-12 pt-2',
    buttonProps: {
      block: false,
      bordered: true,
      circle: false,
      dashed: false,
      disabled: false,
      focusable: true,
      fullWidth: false,
      align: 'left',
      ghost: false,
      round: false,
      secondary: false,
      size: 'medium',
      type: 'default',
    },
    name: 'Naive Button',
    description: 'Naive UI button',
    label: 'Button',
  },
  {
    $formkit: 'submit',
    outerClass: 'col-span-12 pt-2',
    type: 'submit',
    name: 'Submit Button',
    description: 'Allows form submission',
    label: 'Submit',
  },
  {
    $formkit: 'group',
    name: 'Group',
    label: 'Group',
    id: 'group_field',
    outerClass: 'col-span-12',
    description: 'Object grouping of fields',
  },
  {
    $formkit: 'list',
    name: 'List',
    label: 'List',
    id: 'list_field',
    outerClass: 'col-span-12',
    description: 'Array grouping of fields',
  },
]
