import {
  Calendar,
  CalendarClock,
  CircleDot,
  Clock,
  Hash,
  LetterText,
  Link2,
  List,
  Lock,
  Mail,
  Paperclip,
  Phone,
  SlidersHorizontal,
  SquareCheck,
  Type,
  Pipette,
  SendHorizonal,
  SquareMousePointer,
  Group,
  ListTree,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
} from 'lucide-vue-next'

export { defaultFormElements } from './default-form-elements'

export type { FormKitSchemaFormKit } from '@formkit/core'

export const fieldProps = [
  {
    name: 'text',
    tooltip: 'Allows user to enter text',
    icon: Type,
    category: 'fields',
  },
  {
    name: 'email',
    tooltip: 'Allows user to enter email',
    icon: Mail,
    category: 'fields',
  },
  {
    name: 'color',
    tooltip: 'Allows user to select color',
    icon: Pipette,
    category: 'fields',
  },
  {
    name: 'number',
    tooltip: 'Allows user to enter number',
    icon: Hash,
    category: 'fields',
  },
  {
    name: 'checkbox',
    tooltip: 'Allows user to select multiple options',
    icon: SquareCheck,
    category: 'fields',
  },
  {
    name: 'date',
    tooltip: 'Allows user to select date',
    icon: Calendar,
    category: 'fields',
  },
  {
    name: 'datetime-local',
    tooltip: 'Allows user to select date and time',
    icon: CalendarClock,
    category: 'fields',
  },
  {
    name: 'date-time',
    tooltip: 'Allows user to select date and time',
    icon: CalendarClock,
    category: 'fields',
  },
  {
    name: 'file',
    tooltip: 'Allows user to upload file',
    icon: Paperclip,
    category: 'fields',
  },
  {
    name: 'password',
    tooltip: 'Allows user to enter password',
    icon: Lock,
    category: 'fields',
  },
  {
    name: 'radio',
    tooltip: 'Allows user to select single option',
    icon: CircleDot,
    category: 'fields',
  },
  {
    name: 'range',
    tooltip: 'Allows user to select between a range of values',
    icon: SlidersHorizontal,
    category: 'fields',
  },
  {
    name: 'select',
    tooltip: 'Allows user to select from a list of options',
    icon: List,
    category: 'fields',
  },
  {
    name: 'naiveCascader',
    tooltip: 'Allows user to select from a cascader',
    icon: List,
    category: 'fields',
  },
  {
    name: 'naiveTreeSelect',
    tooltip: 'Allows user to select from a tree',
    icon: ListTree,
    category: 'fields',
  },
  {
    name: 'naiveMention',
    tooltip: 'Allows user to mention options',
    icon: LetterText,
    category: 'fields',
  },
  {
    name: 'naiveRate',
    tooltip: 'Allows user to rate with stars',
    icon: SlidersHorizontal,
    category: 'fields',
  },
  {
    name: 'naiveSwitch',
    tooltip: 'Allows user to toggle a boolean value',
    icon: SquareCheck,
    category: 'fields',
  },
  {
    name: 'naiveCheckbox',
    tooltip: 'Allows user to toggle a checkbox value',
    icon: SquareCheck,
    category: 'fields',
  },
  {
    name: 'naiveAvatar',
    tooltip: 'Avatar display',
    icon: SquareMousePointer,
    category: 'fields',
  },
  {
    name: 'tel',
    tooltip: 'Allows user to enter telephone number',
    icon: Phone,
    category: 'fields',
  },
  {
    name: 'textarea',
    tooltip: 'Allows user to enter multiple lines of text',
    icon: LetterText,
    category: 'fields',
  },
  {
    name: 'time',
    tooltip: 'Allows user to select time',
    icon: Clock,
    category: 'fields',
  },
  {
    name: 'url',
    tooltip: 'Allows user to enter url',
    icon: Link2,
    category: 'fields',
  },
  {
    name: 'submit',
    tooltip: 'Allows user to submit form',
    icon: SendHorizonal,
    category: 'static',
  },
  {
    name: 'naiveButton',
    tooltip: 'Naive UI button',
    icon: SquareMousePointer,
    category: 'static',
  },
  {
    name: 'naiveText',
    tooltip: 'Typography text',
    icon: LetterText,
    category: 'static',
  },
  {
    name: 'naiveP',
    tooltip: 'Typography paragraph',
    icon: LetterText,
    category: 'static',
  },
  {
    name: 'naiveA',
    tooltip: 'Typography link',
    icon: Link2,
    category: 'static',
  },
  {
    name: 'naiveBlockquote',
    tooltip: 'Typography blockquote',
    icon: LetterText,
    category: 'static',
  },
  {
    name: 'naiveHr',
    tooltip: 'Typography divider',
    icon: SlidersHorizontal,
    category: 'static',
  },
  {
    name: 'naiveH1',
    tooltip: 'Typography H1',
    icon: Heading1,
    category: 'static',
  },
  {
    name: 'naiveH2',
    tooltip: 'Typography H2',
    icon: Heading2,
    category: 'static',
  },
  {
    name: 'naiveH3',
    tooltip: 'Typography H3',
    icon: Heading3,
    category: 'static',
  },
  {
    name: 'naiveH4',
    tooltip: 'Typography H4',
    icon: Heading4,
    category: 'static',
  },
  {
    name: 'naiveH5',
    tooltip: 'Typography H5',
    icon: Heading5,
    category: 'static',
  },
  {
    name: 'naiveH6',
    tooltip: 'Typography H6',
    icon: Heading6,
    category: 'static',
  },
  {
    name: 'naiveUl',
    tooltip: 'Typography unordered list',
    icon: List,
    category: 'static',
  },
  {
    name: 'naiveOl',
    tooltip: 'Typography ordered list',
    icon: List,
    category: 'static',
  },
  {
    name: 'naiveLi',
    tooltip: 'Typography list item',
    icon: List,
    category: 'static',
  },
  {
    name: 'naiveDivider',
    tooltip: 'Naive UI divider',
    icon: SlidersHorizontal,
    category: 'static',
  },
  {
    name: 'group',
    tooltip: 'Allows user to group fields together',
    icon: Group,
    category: 'structure',
  },
  {
    name: 'list',
    tooltip: 'Allows user to group fields into an array',
    icon: ListTree,
    category: 'structure',
  },
]
